mysql:
  host: ${MYSQL_HOST:localhost}
  port: ${MYSQL_PORT:3306}
  username: ${MYSQL_USER:root}
  password: ${MYSQL_PASS:}
  db: ${MYSQL_DB:zipkin}
zipkin:
  collector:
    port: ${COLLECTOR_PORT:9410}
  store:
    type: ${STORAGE_TYPE:inMemory}
logging:
  level:
# Silence Invalid method name: '__can__finagle__trace__v3__'
    com.facebook.swift.service.ThriftServiceProcessor: 'OFF'
server:
  port: ${QUERY_PORT:9411}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
# add this for mysql tracing: &statementInterceptors=com.github.kristofa.brave.mysql.MySQLStatementInterceptor
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.db}?autoReconnect=true
    username: ${mysql.username}
    password: ${mysql.password}
    schema: classpath:/mysql.sql
# Switch this on to create the schema on startup:
    initialize: false
